# Site settings
title: Knowledge Base
email: info@axismaps.com
description: Knowledge Base - Design. Code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
collections:
  kb_code:
    layout: doc
    output: true
    permalink: /code/:path/
  kb_data:
    layout: doc
    output: true
    permalink: /data/:path/

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
